#!/usr/bin/env bash
set -e

HERE=$(dirname "$0")
. "$HERE"/common

docker build -t "$COMMIT_TAG" "$HERE"/../

docker push "$COMMIT_TAG"
docker tag "$COMMIT_TAG" "$BRANCH_TAG"
docker push "$BRANCH_TAG"
