#!/usr/bin/env bash
set -e

HERE=$(dirname "$0")
ROOT=$(realpath $HERE/..)

# Change the branch here to pull in future schemas
OUTPACK_BRANCH=mrc-4230
REPO=$(mktemp -u)

git clone --branch $OUTPACK_BRANCH https://github.com/mrc-ide/outpack $REPO

DEST=$ROOT/schema/outpack
rm -rf $DEST
cp -r $REPO/schema $DEST

cp $REPO/schema/hash.json $ROOT/schema/server/
cp $REPO/schema/location.json $ROOT/schema/server/
cp $REPO/schema/packet-id.json $ROOT/schema/server/

rm -rf $REPO
